### ISSUE TITLE
Download doesn't work on real device

### ISSUE THREAD

**Issue by razvanrujoiu** [curia-damiano/SwiftUIDownloader#1]
@curia-damiano the app works great on simulator, but on the real device is not working at all. You press download and nothing is happening, it stays at 0%.

**Comment by curia-damiano** [comment]
Hi @razvanrujoiu,
The same issue happens on both the physical device and the simulator.
Essentially, when you start to play a bit too much with background downloads, iOS limits them.
As you demand background downloads to the iOS, you can't do much to control them.

If you have multiple background downlods, you can queue them.
But even in my sample, with 3 background downlods, you can run them - unless iOS wants too...

I'm sorry for there is not even an API to reset the status of your app... you usually wait 5 minutes and then they start.

See for example this discussion: https://stackoverflow.com/questions/33729000/background-download-gets-stuck-after-one-set-of-videos-in-ios-app and 
Also, are you sure that you haven't enabled Low Data Mode on your iPhone? https://support.apple.com/en-ca/HT210596

**Comment by razvanrujoiu** [comment]
@curia-damiano you are right, the issue was that i had Low Data Mode enabled on the device. Thank you, you saved my day! 🙌

**Comment by curia-damiano** [comment]
You're welcome @razvanrujoiu, I've been very happy to be able to help you!

**Comment by razvanrujoiu** [comment]
@curia-damiano i have found  a solution for this issue, actually we could configure the URLSession to allow downloading on Low data mode. 
`session.configuration.allowsConstrainedNetworkAccess = true`

**Comment by curia-damiano** [comment]
hi @razvanrujoiu, now I am on holiday with very bad internet.
When I will be back, I will test this. If it really works, I will add this option to the demo (UI and view models).
Thank you for your inputs!
Regards, Damiano

**Comment by razvanrujoiu** [comment]
@curia-damiano  I will create a PR, and you can test it and we could merge it when you come back. Happy holiday!

**Comment by curia-damiano** [comment]
Thank you @razvanrujoiu for your offer!
Meanwhile I have extended the sample adding the following properties: waitsForConnectivity, allowCellularAccess, allowsConstrainedNetworkAccess and allowsExpensiveNetworkAccess. These are 4 checkboxes in the UI, bound to properties in the view models.
Before committing, I want to do proper tests on my device, when I will back at home.

**Comment by curia-damiano** [comment]
A final comment for @razvanrujoiu: first of all, thank you for using my code!
I am not a full time Swift developer, I try to write samples following the Apple documentation, and the fact that you use it, makes me very proud!

Then: I have given up with the idea of checkboxes and so on. It was good to test the effect of the various options, but it would have required many changes to the view models. The URLSessions are static variables, so after each change, the user would have needed to restart the app. And this was complicating the UI and the view models themselves.

As my idea would be that the view models should be easily reusable, I have chosen to add this code inline. It is also commented, but for each case it is clear where these settings can be used.
Also I have removed allowsExpensiveNetworkAccess because the documentation is not totally clear, and it suggests to use allowsConstrainedNetworkAccess, that I already have.

I have also updated my blog article [SwiftUI Background Downloads](https://curia.me/swiftui-background-downloads/).
